using System.Text;

public class Simulation {
    // Which frames should new clown cars be loaded?
    List<int> LoadOnFrames = new();

    public int[] Directions;

    public bool OnlyLogResult { get; set; }
    public int Cars { get; set; } = 1;
    public int ExtraLoadFramePosition { get; set; } = 0;

    public int Length = 2000;
    public int Frame = 0;
    int InitX = 0;
    public int X = 0;

    public bool Stop = false;

    StringBuilder CSVContentBuilder = new StringBuilder();

    public Simulation(int initialX, int cars) {
        InitX = initialX;
        Cars = cars;
        RNG.Init();

        Directions = new int[Cars];

        RandDiscard(initialX, "Initial X");
    }

    public void AddCSVRow(int x, uint w, string cause, uint result) {
        CSVContentBuilder.Append($"{x};{w};{cause};{(result == 9999999 ? "N/A" : result)};{Frame};;=BITRSHIFT(INDIRECT(\"B\" & ROW()) * 170, 32) + 10;=MOD(INDIRECT(\"B\" & ROW()), 2)\n");
    }

    public void WriteToCSV() {
        using (StreamWriter sw = new StreamWriter(File.Create("result.csv"))) {
            sw.Write("Generated by Clown car RNG Simulator;;;Result;Initial X;ELFP;Frames;Cars\n");
            string leftright = Directions.Select((d) => d == 0 ? "R" : "L").Aggregate((d1, d2) => d1 + d2);
            sw.Write($";;;{leftright};{InitX};{ExtraLoadFramePosition};{Length};{Cars}\n\n");
            sw.Write($"X;RNG state (w);Call reason;Result;Frame;;Blink timer;Stun direction\n");
            sw.Write(CSVContentBuilder.ToString());
        }
    }

    public List<ClownCar> ClownCars = new();

    public void GenerateLoadFrames(int offset = 1) {
        // Specifically for rhymes with toad: spawn 2 more clown cars right away
        LoadOnFrames.Add(1);
        LoadOnFrames.Add(1);
        for (int i = 0; i < Cars; i++) {
            LoadOnFrames.Add(offset);
            // Clown cars in the level are 37 1/3 frames of running apart
            // So we offset by 37 and add 1 every 3 loads
            offset += 37;
            if ((i + ExtraLoadFramePosition) % 3 == 0) offset++;
        }

        Program.Log($"Load frames: [{LoadOnFrames.Select((f) => f.ToString()).Aggregate((f1, f2) => f1 + ", " + f2)}]", true);
    }

    public void Log(string text) {
        if (OnlyLogResult) return;
        Program.Log($"F{Frame}: {text}");
    }

    /// Generate <count> random numbers and discard them
    public void RandDiscard(int count = 1, string reason = "") {
        for (int i = 0; i < count; i++) {
            X++;
            uint w = RNG.Xorshift();
            AddCSVRow(X, w, reason, 9999999);
        }
    }

    /// Generate new blink timer (rand(170) + 10)
    public uint RandBlinkInterval(int id) {
        uint w = RNG.Xorshift();
        uint val = 10 + (uint)((float)w/UInt32.MaxValue * 170) >> 32;
        X++;
        AddCSVRow(X, w, $"({id}) Blink timer", val);
        Program.Log($"New blink interval generated: {val}", true);
        return val;
    }

    /// Generate stun direction after hitting spike (w_n % 2)
    public uint RandSpikeDirection(int id) {
        uint w = RNG.Xorshift();
        uint val = w % 2;
        X++;
        AddCSVRow(X, w, $"({id}) Stun direction", val);
        Program.Log($"New spike direction generated: {val}", true);
        return val;
    }

    public int[] Start() {
        GenerateLoadFrames();

        if (!OnlyLogResult) Program.Log("=== SIMULATION START ===");
        while (Frame < Length && !Stop) FrameAdvance();
        if (!OnlyLogResult) Program.Log($"=== SIMULATION END ({Frame} frames) ===");

        string leftright = Directions.Select((d) => d == 0 ? "R" : "L").Aggregate((d1, d2) => d1 + d2);
        //Program.Log($"Result (init X {InitX}, ELFP {ExtraLoadFramePosition}): clown cars move {leftright}");

        WriteToCSV();

        CSVContentBuilder = null; // To prevent memory overusage
        return Directions;
    }

    public void FrameAdvance() {
        Frame++;

        RandDiscard(reason: "Player run");

        for (int i = ClownCars.Count; i > 0; i--) {
            ClownCars.Where((cc) => cc.ID == i).First().Update();
        }

        if (LoadOnFrames.Contains(Frame)) LoadClownCar();
    }

    private void LoadClownCar() {
        Log("Loading a new clown car");
        ClownCar cc = new ClownCar(this);
        ClownCars.Add(cc);
        cc.ID = ClownCars.Count;
        if (cc.ID <= 3) cc.HasUniqueDeloadTime = true;
        RandDiscard(3, $"({cc.ID}) Clown car load"); // Clown car 3X
        cc.BlinkInterval = RandBlinkInterval(cc.ID);
    }
}